# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Jitsi SCTP

on: push

jobs:
  build:
    
    strategy:
      matrix:
        platform: [ubuntu-latest] # , macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    
    name: "build usrsctp and jniwrapper-native"
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: actions-setup-cmake
      uses: jwlawson/actions-setup-cmake@v1.2

    - name: Build with Maven and publish to GitHub Packages Apache Maven
      env:
        GITHUB_USERNAME: mstyura
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B -X -Dmaven.wagon.http.pool=false package deploy --file pom.xml --projects org.jitsi:usrsctp,org.jitsi:jniwrapper-native --also-make --activate-profiles build-usrsctp,build-jnisctp -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/mstyura/jitsi-sctp/

