# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Jitsi SCTP

on: push

jobs:
  build:
    
    strategy:
      matrix:
        platform: [ubuntu-latest] # , macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    
    name: "build usrsctp and jniwrapper-native"
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodule: recursive
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: actions-setup-cmake
      uses: jwlawson/actions-setup-cmake@v1.2

    - name: Build with Maven
      run: mvn -B package --file pom.xml --projects org.jitsi:usrsctp,org.jitsi:jniwrapper-native --also-make --activate-profiles build-usrsctp,build-jnisctp

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn -B deploy --projects org.jitsi:usrsctp,org.jitsi:jniwrapper-native
      env:
        GITHUB_TOKEN: ${{ github.token }}
